name: "lvCICD"
author: "NEVSTOP-LAB"
description: "CICD Action used for LabVIEW Users"
branding:
  icon: "anchor"
  color: "green"

inputs:
  LabVIEW_Version:
    description: "LabVIEW Version Used"
    required: false
    default: "2020"
  Architecture:
    description: "32bit/64bit Version of LabVIEW Used"
    required: false
    default: "x86"
  OperationVIFolder:
    description: "Path Contains the Operation VIs"
    required: false
    default: ""
  Operation:
    description: "The operation of lvCICD"
    required: false
    default: "lvecho"
  Parameter1:
    description: "Parameter of lvCICD"
    required: false
    default: ""
  Parameter2:
    description: "Parameter of lvCICD"
    required: false
    default: ""
  Parameter3:
    description: "Parameter of lvCICD"
    required: false
    default: ""
  Parameter4:
    description: "Parameter of lvCICD"
    required: false
    default: ""
  Parameter5:
    description: "Parameter of lvCICD"
    required: false
    default: ""
  Parameter6:
    description: "Parameter of lvCICD"
    required: false
    default: ""
  Parameter7:
    description: "Parameter of lvCICD"
    required: false
    default: ""
  Parameter8:
    description: "Parameter of lvCICD"
    required: false
    default: ""
  Parameter9:
    description: "Parameter of lvCICD"
    required: false
    default: ""
  Parameter10:
    description: "Parameter of lvCICD"
    required: false
    default: ""
outputs:
  Result:
    description: "Output of lvCICD"
    value: ${{ steps.lvCICDScript.outputs.Result }}
runs:
  using: "composite"

  steps:
    - name: "Checkout-lvCICD-Action"
      uses: actions/checkout@v4.1.1

    # - name: "Show working dir"
    #   run: pwd
    #   shell: powershell

    - name: "Run-lvCICD-Scripts"
      id: lvCICDScript
      run: |
        $Parameter1 = "${{ inputs.Parameter1 }}"; if ( $Parameter1 ) { $Parameter1 = """$Parameter1""" };
        $Parameter2 = "${{ inputs.Parameter2 }}"; if ( $Parameter2 ) { $Parameter2 = """$Parameter2""" };
        $Parameter3 = "${{ inputs.Parameter3 }}"; if ( $Parameter3 ) { $Parameter3 = """$Parameter3""" };
        $Parameter4 = "${{ inputs.Parameter4 }}"; if ( $Parameter4 ) { $Parameter4 = """$Parameter4""" };
        $Parameter5 = "${{ inputs.Parameter5 }}"; if ( $Parameter5 ) { $Parameter5 = """$Parameter5""" };
        $Parameter6 = "${{ inputs.Parameter6 }}"; if ( $Parameter6 ) { $Parameter6 = """$Parameter6""" };
        $Parameter7 = "${{ inputs.Parameter7 }}"; if ( $Parameter7 ) { $Parameter7 = """$Parameter7""" };
        $Parameter8 = "${{ inputs.Parameter8 }}"; if ( $Parameter8 ) { $Parameter8 = """$Parameter8""" };
        $Parameter9 = "${{ inputs.Parameter9 }}"; if ( $Parameter9 ) { $Parameter9 = """$Parameter9""" };
        $Parameter10 = "${{ inputs.Parameter10 }}"; if ( $Parameter10 ) { $Parameter10 = """$Parameter10""" };
        ${{ github.action_path }}\lvCICD.ps1 `
        "${{ inputs.LabVIEW_Version }}" `
        "${{ inputs.Architecture }}" `
        "${{ inputs.OperationVIFolder }}" `
        ${{ inputs.Operation }} `
        $Parameter1 `
        $Parameter2 `
        $Parameter3 `
        $Parameter4 `
        $Parameter5 `
        $Parameter6 `
        $Parameter7 `
        $Parameter8 `
        $Parameter9 `
        $Parameter10 ;
        $Result=Get-Content -Path "${{ github.action_path }}\output.txt";
        Write-Host "::set-output name=Result::$Result"
      shell: powershell
